# projectName/.github/config.yml

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: | 
  ## Changes
  $CHANGES
version-resolver:
  minor:
    labels:
      - "BREAKING CHANGE"
  default: patch
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
