name: Semantic_Version
on:
  push:
    # branch:
    #   - "*"
  pull_request:
    # branch:
    #   - "*"
    
jobs:
  semantics_vsrsioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: go-semantic-release/action@v1
        with:
          changelog-file: CHANGELOG.md
          changelog-generator-opt: "emojis=true"
          github-token: ${{ secrets.GITHUB_TOKEN }}

